/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/views/About.vue')['default']
    DashboardLayout: typeof import('./src/components/templates/DashboardLayout.vue')['default']
    Home: typeof import('./src/components/views/Home.vue')['default']
    Login: typeof import('./src/components/views/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
