openapi: "3.0.0"
info:
  version: 1.0.0
  title: BarService
  license:
    name: MIT
servers:
  - url: http://bar.swagger.io/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: uint32
          description: サーバー内部で使用しているエラーコード
          example: "0x800001"
        message:
          type: string
          description: エラーメッセージ (多言語化対象)
          example: |
            インターナルエラーが発生しました。
            (エラーコード: 0x800001)
      required:
        - code
        - message

security: # 全てのエンドポイントに対してbearerの指定を要求する
  - bearerAuth: []

paths:
  /saml/login:
    get:
      tags:
        - Auth API
      description: SAMLでのシングルサインオンを開始します
      security: [] # JWTトークンの指定無効化
      responses:
        '200':
          description: 正常終了
          content:
            text/html:
              schema:
                type: string
                example: |
                  <form>
                  </form>
        default:
          description: 予期しないエラー発生時
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"