openapi: "3.0.0"
info:
  version: 1.0.0
  title: BarService
  license:
    name: MIT
servers:
  - url: http://bar.swagger.io/v1
components:
  securitySchemes:
    cookieAuth:         # arbitrary name for the security scheme; will be used in the "security" key later
      type: apiKey
      in: cookie
      name: access_token
  schemas:
    SAMLForm:
      type: string
      example: |
        example: |
          <!DOCTYPE html>
          <html>
            <body>
              <form method="POST" id="SAMLRequestForm">
                <input name="SAMLRequest" ・・・>
              </form>
              <script>document.getElementById("SAMLRequestForm").submit()</script>
            </body>
          </html>
    SAMLRequest:
      type: object
      properties:
        SAMLReqeust:
          type: string
          example: "PHNhbWxwOlJlc3BvbnNlIHhtbG5zOnNhbWxwPSJ1cm46b2FzaXM6bmFtZXM6d・・・"
        RelayState:
          type: string
          example: "xxx"
    SAMLResponse:
      type: object
      properties:
        SAMLResponse:
          type: string
          example: "PHNhbWxwOlJlc3BvbnNlIHhtbG5zOnNhbWxwPSJ1cm46b2FzaXM6bmFtZXM6d・・・"
        RelayState:
          type: string
          example: "xxx"
    Error:
      type: object
      properties:
        code:
          type: integer
          format: uint32
          description: サーバー内部で使用しているエラーコード
          example: "0x800001"
        message:
          type: string
          description: エラーメッセージ (多言語化対象)
          example: |
            インターナルエラーが発生しました。
            (エラーコード: 0x800001)
      required:
        - code
        - message
    ErrorWithTime:
      type: object
      properties:
        err:
          $ref: "#/components/schemas/Error"
        time:
          type: string
          example: "2024-08-14T11:19:12+09:00"
      required:
        - err
        - time

security: # 全てのエンドポイントに対してbearerの指定を要求する
  - bearerAuth: []

paths:
  /saml/login:
    get:
      tags:
        - Auth API
      summary: ユーザをシングルサインオンさせるログインリクエストを作成し、FormのPOSTによってidPに送信するスクリプトタグを含んだHTMLを返却するエンドポイント。
      security: []
      parameters:
        - name: X-Redirect-URL
          in: header
          required: true
          description: シングルサインオン完了時にリダイレクトさせたいURLを指定する
          schema:
            type: string
            example: "https://xxxxx/"
        - name: X-Redirect-URL-On-Error
          in: header
          required: true
          description: シングルサインオンエラー時にリダイレクトさせたいURLを指定する
          schema:
            type: string
            example: "https://xxxxx/"
      responses:
        '200':
          description: 正常終了
          headers:
            Set-Cookie:
              schema:
                type: string
                example: sso_token=xxxx; Path=/saml/acs; HttpOnly
          content:
            text/html:
              schema:
                $ref: "#/components/schemas/SAMLForm"
        default:
          description: シングルサインオンが許可されなかった場合
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /saml/acs:
    post:
      tags:
        - Auth API
      summary: IdPから受け取る認証レスポンス（SAMLアサーション）を処理するエンドポイント。
      security: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/SAMLResponse"
      responses:
        '302':
          description: |
             正常終了<br>
             (エラーが発生した場合はHttpヘッダのLocationに格納されれているURLにURLパラメータ(saml_error=1)が付与される)
          headers:
            Set-Cookie:
              schema:
                type: string
                example: access_token=xxxx; Path=/; HttpOnly, refresh_token=xxxx; Path=/TODO; HttpOnly, saml_error_token=xxxx; Path=/saml/error; HttpOnly
            Location:
              schema:
                type: string
                example: "https://xxxxx/login?saml_error=1"
              description: リダイレクト先のURL
  /saml/logout:
    get:
      tags:
        - Auth API
      summary: ユーザをログアウトさせるログアウトリクエストを作成し、FormのPOSTによってidPに送信するスクリプトタグを含んだHTMLを返却するエンドポイント。
      security:
        - cookieAuth: []
      parameters:
        - name: X-Redirect-URL
          in: header
          required: true
          description: シングルログアウト完了時にリダイレクトさせたいURLを指定する
          schema:
            type: string
            example: "https://xxxxx/"
        - name: X-Redirect-URL-On-Error
          in: header
          required: true
          description: シングルログアウトのエラー時にリダイレクトさせたいURLを指定する
          schema:
            type: string
            example: "https://xxxxx/"
      responses:
        '200':
          description: 正常終了
          headers:
            Set-Cookie:
              schema:
                type: string
                example: slo_token=xxxx; Path=/saml/slo; HttpOnly
          content:
            text/html:
              schema:
                $ref: "#/components/schemas/SAMLForm"
        default:
          description: シングルサインオンが許可されなかった場合
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /saml/slo:
    post:
      tags:
        - Auth API
      summary: IdPから受け取るログアウトリクエストを処理し、ユーザーをログアウトさせるエンドポイント。
      security:
        - cookieAuth: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              oneOf:
                - $ref: "#/components/schemas/SAMLRequest"
                - $ref: "#/components/schemas/SAMLResponse"
      responses:
        '200':
          description: |
            他SP起点のシングルログアウトが正常終了<br>
          content:
            text/html:
              schema:
                $ref: "#/components/schemas/SAMLForm"
        '302':
          description: |
             本SP起点のシングルログアウトが正常終了<br>
             (エラーが発生した場合はHttpヘッダのLocationに格納されれているURLにURLパラメータ(saml_error=1)が付与される)
          headers:
            Set-Cookie:
              schema:
                type: string
                example: saml_error_token=xxxx; Path=/saml/error; HttpOnly
            Location:
              schema:
                type: string
                example: "https://xxxxx/login?saml_error=1"
              description: リダイレクト先のURL
  /saml/error:
    get:
      tags:
        - Auth API
      summary: SAMLログインのエラー詳細を返却するエンドポイント
      security: []
      responses:
        '200':
          description: 正常終了
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorWithTime"
        default:
          description: 予期しないエラーが発生した場合
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"