
# 一般設定
server:
  port: 8000
  allowOrigins:
    - https://fx-tester-fe:3000
    - https://localhost:3000
  ssl:
    isEnabled: true
    certPath: "{{ .pwd }}/settings/cert/fx-tester.cert.pem"
    keyPath: "{{ .pwd }}/settings/cert/fx-tester.key.pem"
# DB設定
db:
  name: postgres
  dsn: "host=fx-tester-db port=5432 user=app_user password=app_user dbname=fxtester_db sslmode=disable search_path=fxtester_schema"
  maxIdleConnections: 100
  maxOpenConnections: 100
  maxLifeTimeBySec: 60000
# SAML設定
saml:
  # keycloakの設定
  keycloak:
    adminUser:
      username: admin
      password: admin
    baseURL: "http://keycloak:8080"
    realmName: my-realm
    # keycloak初期化と同時に追加するユーザ
    newUsers:
      - username: test
        password: test
        email: test@fxtester.com
    # 新規追加するクライアントのID
    newClientId: fx-tester-client
  idpMetadataUrl: http://keycloak:8080/realms/my-realm/protocol/saml/descriptor
  rootURL: https://fx-tester-fe:3000/
  entityId: https://fx-tester-fe:3000/
  backendURL: https://fx-tester-be:8000/
  validRedirectURI: "https://fx-tester-be:8000/*"
  validPostLogoutRedirectURI: "https://fx-tester-be:8000/*"
  logoutServicePostBindingURL: "https://fx-tester-be:8000/saml/slo"
# 辞書設定
dict:
  path: "{{ .pwd }}/settings/dict.yaml"