version: '3'

services:
  # データベースのコンテナ
  fx-tester-db:
    container_name: fx-tester-db
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    image: postgres
    build:
      context: ../
      dockerfile: docker/postgres/Dockerfile
    volumes:
      - ./postgres/script:/docker-entrypoint-initdb.d
    networks:
      net_fxt:
        ipv4_address: 192.168.254.10

  # フロントエンドのコンテナ
  fx-tester-fe:
    container_name: fx-tester-fe
    restart: always
    ports:
      - "127.0.0.1:3000:80"
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ../../FXTesterWeb/dist:/usr/share/nginx/html
    networks:
      net_fxt:
        ipv4_address: 192.168.254.20
    depends_on:
      - fx-tester-be

  # バックエンドのコンテナ
  fx-tester-be:
    container_name: fx-tester-be
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    build:
      context: ../
      dockerfile: docker/bar/Dockerfile
    networks:
      net_fxt:
        ipv4_address: 192.168.254.30
    depends_on:
      - keycloak
      - fx-tester-db

  # idP
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - keycloak:/opt/keycloak/data/
    restart: always
    command:
      - "start-dev"
    networks:
      net_fxt:
        ipv4_address: 192.168.254.40

networks:
  net_fxt:
    name: net_fxt
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.254.0/24

volumes:
  keycloak: